### ISSUE TITLE
No matching distribution found for tree==0.1.0

### ISSUE THREAD

**Issue by erkhemee** [silicon-valley-data-science/RNN-Tutorial#9] opened 2017-04-16 04:10 UTC
Hi,

Installation has failed. Because, tree-0.1.0 package removed from  https://pypi.python.org/pypi/tree/0.1.0 ?

Installation log:
```
Collecting tree==0.1.0 (from -r requirements.txt (line 11))
  Could not find a version that satisfies the requirement tree==0.1.0 (from -r requirements.txt (line 11)) (from versions: )
No matching distribution found for tree==0.1.0 (from -r requirements.txt (line 11))
```

**Comment by woj-i** [comment] 2017-04-26 10:24
I have the same problem.

**Comment by jupiter126** [comment] 2017-05-03 07:28
Indeed, code runs, but results are so bad that I wonder if it does as intended...

**Comment by jupiter126** [comment] 2017-05-09 07:38
Found the bugger! it is at https://github.com/PixelwarStudio/PyTree
and gets installed when changing requirements.txt tree line to:
Tree==0.1b6
(with a capital!)
or in other words:
pip3 install Tree

**Comment by Leechen2014** [comment] 2017-05-21 07:07
you can run pip install tree , it will install tree==0.1b6

**Comment by mrubashkin-svds** [comment] 2017-06-02 19:00
Merged PR to address issues, thanks everyone

**Closed by mrubashkin-svds** 2017-06-02 19:00 UTC
