### ISSUE TITLE
Showing an error

### ISSUE THREAD

**Issue by vinayakumarr** [silicon-valley-data-science/RNN-Tutorial#5] opened 2017-03-26 10:14 UTC
I have installed Tensorflow 1.0.1 CPU version and when i tried to run your code am getting the below err.

Traceback (most recent call last):
  File "/home/hp/pradeep/RNN-Tutorial-master/src/tests/train_framework/tf_train_ctc_test.py", line 8, in <module>
    import train_framework.tf_train_ctc as tf_train
ImportError: No module named train_framework.tf_train_ctc

**Comment by saurabhvyas** [comment] 2017-03-26 14:13
I am getting the same error , I can confirm this , but it works on my non gpu laptop

**Comment by mrubashkin-svds** [comment] 2017-03-27 16:16
@saurabhvyas @vinayakumarr can you confirm what your system PYTHONPATH is set to (echo $PYTHONPATH)?

This error could be caused by the tf_train_ctc.py not being able to see the other modules included in the RNN-Tutorial repository to import

**Comment by vinayakumarr** [comment] 2017-03-28 05:05
/home/hp/pradeep/RNN-Tutorial-master/src:/home/hp/pradeep/RNN-Tutorial-master/src:/home/hp/pradeep/RNN-Tutorial-master/src:/home/hp/pradeep/RNN-Tutorial-master/src:/home/hp/pradeep/RNN-Tutorial-master/src:

RNN-Tutorial-master exists in /home/hp/pradeep/RNN-Tutorial-master

**Comment by vinayakumarr** [comment] 2017-03-29 11:29
/home/hp/pradeep/RNN-Tutorial-master/src:/home/hp/pradeep/RNN-Tutorial-master/src:/home/hp/pradeep/RNN-Tutorial-master/src:/home/hp/pradeep/RNN-Tutorial-master/src:/home/hp/pradeep/RNN-Tutorial-master/src:

RNN-Tutorial-master exists in /home/hp/pradeep/RNN-Tutorial-master

**Comment by mrubashkin-svds** [comment] 2017-03-29 18:57
@vinayakumarr Thanks for the info. Are you running this from the command line or from a console like Jupyter? If you are in a console, could you try and hardest some of the env variables before the import:

```
os.environ['RNN_TUTORIAL'] = '/home/hp/pradeep/RNN-Tutorial-master'
os.environ['PYTHONPATH']='/home/hp/pradeep/RNN-Tutorial-master/src:/home/hp/pradeep/RNN-Tutorial-master/src:'
```

**Comment by mrubashkin-svds** [comment] 2017-04-06 15:33
Closing this issue, as setting the environment variables inside of Jupyter or having jupyter inherit these environment variables solved the problem

**Closed by mrubashkin-svds** 2017-04-06 15:33 UTC
